project_id = "kivgbkgistppjmcqpngo"

[functions.bot-sync]
verify_jwt = false

[functions.bot-commands]
verify_jwt = false

[functions.bot-params]
verify_jwt = false

[functions.heartbeat-watchdog]
verify_jwt = false

[functions.send-forecast]
verify_jwt = false
