ALTER TABLE public.bot_params
  ADD COLUMN IF NOT EXISTS tp_multiplier NUMERIC NOT NULL DEFAULT 2.0,
  ADD COLUMN IF NOT EXISTS use_trailing_stop BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS trailing_stop_activation_pips NUMERIC NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS trailing_stop_distance_pips NUMERIC NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS use_break_even BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS break_even_activation_pips NUMERIC NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS daily_profit_target NUMERIC NOT NULL DEFAULT 0;